name: boptestgym # Name is ignored if using --prefix
channels:
  - defaults
  - conda-forge
  # Optional: Add pytorch channel if you prefer installing torch via conda
  # - pytorch
dependencies:
  - python=3.10
  - pip
  - setuptools
  - wheel
  - cffi
  - cryptography
  - pyopenssl
  - requests
  - readline
  - openssl
  - tk
  - sqlite
  - zlib
  - notebook
  # Add other conda packages if needed
  - numpy # Better handled by conda usually
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - pip:
      - cloudpickle==2.2.1
      # - cmake==3.26.4 # Often needed for building dependencies
      - contourpy==1.1.0
      - cycler==0.11.0
      - farama-notifications==0.0.4
      - filelock==3.12.2
      - fonttools==4.40.0
      # - gym==0.26.2 # superseded by gymnasium
      - gym-notices==0.0.8
      - gymnasium==0.28.1
      # - jax-jumpy==1.0.0 # Unlikely needed unless using JAX
      - jinja2==3.1.2
      - kiwisolver==1.4.4
      # - lit==16.0.6 # LLVM related, might not be needed directly
      - markupsafe==2.1.3
      # - mpmath==1.3.0 # Used by sympy
      - networkx==3.1
      - packaging==23.1
      - pillow==10.0.0
      - pyparsing==3.1.0
      - python-dateutil==2.8.2
      - pytz==2023.3
      - shimmy==1.1.0
      - six==1.16.0
      - stable-baselines3==2.0.0 # Keep SB3
      - sympy==1.12
      # - torch==2.0.1 # REMOVE - Install separately via pip for specific CUDA
      # - triton==2.0.0 # REMOVE - Let torch handle it
      - typing-extensions==4.7.1
      - tzdata==2023.3
      # --- ADDED MISSING PACKAGES ---
      - sb3-contrib # For MaskablePPO
      - boptest-gym # For BOPTEST interaction
      - hydra-core  # For Hydra config
      - omegaconf   # Hydra dependency
      # - hydra-submitit-launcher # Optional: if using hydra launcher later
      # --- REMOVED nvidia-* packages ---