defaults:
  - ppo_masked

# Hydra settings for submitit Slurm here
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S}
  launcher:
    name: submitit_slurm

env:
  url: "http://localhost:5001"
  actions: ["oveHeaPumY_u"]
  step_period: 3600
  # any other environment params

model:
  # Defaults for MaskablePPO
  policy: "MlpPolicy"
  gamma: 0.99
  learning_rate: 5e-4
  verbose: 1
  seed: 4

training:
  total_timesteps: 10_000